site_name: VisAPI Documentation
theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: switch to light mode

  features:
    - navigation.tracking
    #    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
    - toc.follow
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github-alt

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.blocks.tab:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

# repo
repo_name: VisAPI
repo_url: https://github.com/vanker-x/VisAPI

nav:
  - Overview: index.md
  - Installation: installation.md
  - Guide:
      - guide/index.md
      - Tutorial:
          - guide/tutorial/index.md
          - Application: guide/tutorial/application.md
          - Callback: guide/tutorial/callback.md
          - Configuration: guide/tutorial/configuration.md
          - Routing:
              - guide/tutorial/routing/index.md
              - Router: guide/tutorial/routing/router.md
              - Route: guide/tutorial/routing/route.md
              - Convertor: guide/tutorial/routing/convertor.md
          - Group: guide/tutorial/group.md
          - Visualization: guide/tutorial/visualization.md
          - Request: guide/tutorial/request.md
          - Response: guide/tutorial/response.md
          - Websocket: guide/tutorial/websocket.md
      - Cakes:
          - guide/cakes/index.md
          - Specification:
              - guide/cakes/specification/index.md
              - WSGI: guide/cakes/specification/WSGI.md
              - ASGI: guide/cakes/specification/ASGI.md
              - RSGI: guide/cakes/specification/RSGI.md
          - Sqlalchemy: guide/cakes/sqlalchemy.md
          - Pydantic: guide/cakes/pydantic.md
      - Deployment:
          - guide/deployment/index.md
          - granian: guide/deployment/granian.md
          - uvicorn: guide/deployment/uvicorn.md
  - Reference:
      reference/index.md

plugins:
  - glightbox
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: ç®€ä½“ä¸­æ–‡
          build: true
          site_name: VisAPI ä¸­æ–‡æ–‡æ¡£
          nav_translations:
            Home: åºè¨€
            Guide: æŒ‡å—
            Reference: å‚è€ƒ
            Routing: è·¯ç”±ç³»ç»Ÿ
            Router: è·¯ç”±å™¨
            Route: è·¯ç”±
            Convertor: è·¯ç”±è½¬æ¢å™¨
            Application: åº”ç”¨
            Callback: å›è°ƒ
            Configuration: é…ç½®
            Installation: å®‰è£…
            Tutorial: æ•™ç¨‹
            Group: ç»„
            Visualization: å¯è§†åŒ–
            Request: è¯·æ±‚
            Response: å“åº”
            Cakes: ä¸€äº›å°è›‹ç³•ğŸ§
            Specification: è§„æ ¼
            Deployment: éƒ¨ç½²


extra_css:
  - stylesheets/extra.css